### ISSUE TITLE
options in osara's configuration window out of the tab order

### ISSUE THREAD

**Issue by GianlucaApollaro** [nvaccess/osara#102]
when going into the osara configuration window, the check boxes to toggle the various options are not in the tab order anymore. They can be reached with left or right arrows, but with the tab key, only the ok and the cancel button show up. Using latest reaper, osara, and it happens in both jaws and NVDA.

**Comment by jcsteh** [comment]
Confirmed. Regression introduced by 10c7e8c1. Investigating.

**Comment by jcsteh** [comment]
@mulcahy1000, just a heads up for future reference: when using the CONTROL command with BS_AUTOCHECKBOX (instead of the aAUTOCHECKBOX command which swell_resgen doesn't support), you must explicitly specify WS_TABSTOP as well. Clearly, I didn't test this well enough when I committed it. :)
