### ISSUE TITLE
Document how to discover commands

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/osara#116]
Hi:
As someone who has never used reaper before, I wasn't aware what the big lists of commands such as 
Edit: delete notes of less than 1/16 note in length in selected MIDI items
on the main page mean. Could a note be added to the readme to explain that you can discover a key binding by pasting the command in the list into the filter dialog after pressing f4? The f4 thing wasn't obvious, until a friend told me it exists. 
Also, can a note be added in the readme to explain what all the lists of commands mean? Maybe just a bit of background as to why the readme's usage section is laid out as it is. 
It may be that I am new to reaper and getting confused, but I had trouble understanding what to make of the usage section at first.
Thanks

**Comment by jcsteh** [comment]
At this stage, the OSARA documentation is only intended to document stuff specific to OSARA; i.e. the actions it supports, OSARA specific functionality, etc. You're expected to refer to other sources for information about REAPER which is not specific to OSARA (and the Actions dialog, etc. is not OSARA functionality; it's part of REAPER). It's akin to the NVDA User Guide, which is a reference that does not explain Windows concepts.

Eventually, we'll need to have a tutorial or the like which introduces the fundamental concepts of REAPER for OSARA users. This is akin to the NVDA training modules: they do explain Windows concepts, word processing concepts, etc. This is not something we have the resources to put together at this stage, and if we did, it would be at cost (like the NVDA training modules). I believe there are others who are looking into this, though.

I'm closing this for now. That said, I'll be happy to include any tutorial style documentation with OSARA should it be developed.
