### ISSUE TITLE
Access Monitor FX parameters

### ISSUE THREAD

**Issue by marioloreti** [nvaccess/osara#117]
I would to have access the monitor FX parameters because there are some plugins that allow you to fix some headphone equalization, and it will be usefull to not have to put them on the master track everytime, so that they do not get rendered with the project.

**Comment by chrisbelle2015** [comment]
Also some folks in the studio like to have fx like reverb while tracking 
but you don't necessarily want them rendered.
yes, you can by-pass when rendering, but this is still a useful thing to 
have.
So I'll add my request for this as well, thank you kindly.
