### ISSUE TITLE
Selecting contiguous items

### ISSUE THREAD

**Issue by GianlucaApollaro** [nvaccess/osara#12]
Hi, selecting contiguous items on a track would be good. I did it using the sws actions select next item, keeping current selection (across tracks) and of course, select previous item, keeping current selection (across tracks). This works, but in rea-access we had the cursor moving to the selected item that therefore was playing, but more inportantly we had the number of selected items reported and spoken.
I think two new custom actions might be required
Thanks as always and keep up the good work

**Comment by jcsteh** [comment]
I agree we need actions to select contiguous items, though as you pointed out, SWS has these and we could just tweak them in a similar way to the way normal item navigation is handled. However, I'm not sure I agree with announcing the number of selected items. That could get very annoying. I guess you can silence it if needed, but it's also inconsistent with the way selection is handled everywhere else. For example, when you select text, you only hear the text you just selected, not the entire selection every time or a count of selected characters. Can you explain why this should be any different? I'd be happy to consider a command for reporting selection information, though, since it's certainly true that sighted users could see this easily enough.

**Comment by GianlucaApollaro** [comment]
Hi,
I tried different things to tweak them chaining different actions, but 
it was not working reliably enough. Here's why I think it could be good 
to have the number of selected item spoken. Here's what happens in 
rea-access. Let's say we have  a track with 4 items on it. We select all 
4 of them by pressing ctrlShift and right arrow; each time we press the 
key, the corresponding item starts playing and it gets selected. At this 
point we go back with ctrl shift and the left arrow. Although the item 
playing, in our case, would be the item 3, the selected items are still 
4 and I know it because reaccess tells me 4 items selected. Basically 
when you go back you are not unselecting the item you just passed, and 
sws has the same behaviour from what I could see.
Sorry for the lenght of this post, but I hope I explained myself well

Il 06/03/2015 03:05, jcsteh ha scritto:

**Comment by chrisbelle2015** [comment]
Nice one Jamie.

It took me a minute to figure out how that worked,
the one action puts it in the mode and then you use the other one to 
read the status of selected or unselected.
Then you go back to the other action to toggle it.
I hope I'm using it correctly, that seems how it's working for me.
I"m actually starting  to feel nominally competent with reaper to where 
I don't have to sit in the dum dum corner every single day pondering why 
reaper didn't do something simple I asked it to do, ha.\


On 11/13/2015 6:09 PM, James Teh wrote:
>
> Closed #12 <https://github.com/nvaccess/osara/issues/12> via 02652dd 
> <https://github.com/nvaccess/osara/commit/02652ddef8eb6ca7fdaf94780082f79c6c77aeb7>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/osara/issues/12#event-464194978>.
>


---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by jcsteh** [comment]
If you want contiguous selection, you don't have to enable any mode. You 
just use the "keep selection" actions. If you want noncontiguous, you 
engage it with toggle selection, then use tggle selection thereafter 
to... well... toggle selection. :)

You don't need to keep using report selection. The item movement actions 
OSARA supports will tell you each item as you move to it, including 
whether or not it's selected. Note that you'll need to bind the new item 
keep selection actions yourself, as they certainly won't be in the DG 
keymap yet.

**Comment by chrisbelle2015** [comment]
yeh, I did bind both the new actions.

This is going to make things a lot easier.
Nice one Jamie.



On 11/14/2015 2:28 PM, James Teh wrote:
> If you want contiguous selection, you don't have to enable any mode. You
> just use the "keep selection" actions. If you want noncontiguous, you
> engage it with toggle selection, then use tggle selection thereafter
> to... well... toggle selection. :)
>
> You don't need to keep using report selection. The item movement actions
> OSARA supports will tell you each item as you move to it, including
> whether or not it's selected. Note that you'll need to bind the new item
> keep selection actions yourself, as they certainly won't be in the DG
> keymap yet.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/osara/issues/12#issuecomment-156744070>.
>


---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus
