### ISSUE TITLE
Keyboard help

### ISSUE THREAD

**Issue by RustyPerez** [nvaccess/osara#14]
Hi Jamie, It would be nice to have a keyboard learn or keyboard help mode so that OSARA would report the assigned function of a given key-press. Thanks for your hard work!

**Comment by jcsteh** [comment]
There are a few reasons I'm reluctant to implement this (or at least think it is very low priority):

1. REAPER actually already has this functionality via the Find shortcut button in the Actions dialog. Thus, the experience is the same for both screen reader and sighted users.
2. This is very much specific to screen readers. I can't think of another application (other than a screen reader) that implements this for its own commands. For example, there's no mode in, say, Microsoft Word that allows you to press control+b and informs you that it toggles bold.

**Comment by ScottChesworth** [comment]
Struck a compromise with Jamie on this one that it will be implemented once some funding is secured for the time it'll take to develop. I'm working on that and am hopeful that we'll have support soon, but feel free to donate if it's a topic close to your heart. Tbh, until we're closer to settling on a keymap, it makes sense that this is low-ish priority anyway.
