### ISSUE TITLE
Add context sensitivity and action feedback for deletion of markers

### ISSUE THREAD

**Issue by GianlucaApollaro** [nvaccess/osara#18]
I would like to have the action OSARA: Remove items/tracks/contents of time selection (depending on focus) delete also project, tempo and stretch markers Depending on focus and get action feedback

**Comment by jcsteh** [comment]
I assume this also means you need special support for actions to move to 
previous and next stretch markers? REAPER doesn't internally have an 
idea of "focus" for stretch markers, so we'd have to fake this.

**Comment by GianlucaApollaro** [comment]
There actually are actions that move the cursor to previous and next 
stretch marker: They are go to previous and go to next stretch marker.
There is also remove sthretch marker at current position, it'd be good 
to have that mapped to the delete key and have feedback for all 3
Il 25/03/2015 13:51, jcsteh ha scritto:

**Comment by jcsteh** [comment]
I know there are actions for next/prev stretch marker, but OSARA doesn't 
know about them yet. I guess my question is: is this the only way you 
move to stretch markers? Basically, I need to teach OSARA when it should 
do fake focus for stretch markers. Also, do you want any action feedback 
for next/prev stretch marker?

**Comment by GianlucaApollaro** [comment]
Hi, yes, this is the only way I know. It would be cool, more than the 
feedback, to make the cursor play as we move, a bit like when we move to 
next item
Thanks and keep it up
Il 25/03/2015 21:57, jcsteh ha scritto:
