### ISSUE TITLE
Investigate Track I/O window behavior

### ISSUE THREAD

**Issue by cmdfv** [nvaccess/osara#24]
In the Track I/O window (action: "Track: view I/O for current track"), you can't tell which delete button is for which send in your project when tabbing through. ReAccess must be doing something to get the track send name.
Moreover, some things that are visible using flat review/obj nav don't show up in the tab order.

Please investigate the dialog and see if there's a way to make some of these things speak. This includes pre/post fader, sending to other channels on a multichannel track.

Notes: with flat review, I can see which send goes to which track and the delete button, and tested it with success. There's a line above the delete button that says "send to track foo". If I hit the button below that line in flat review, the send going to foo  goes away.

Once we know more about this dialog from a true screen reading/MSAA point of view, we can talk about working around it. I don't wanna go suggesting things that might be impossible or a lot of extra work if we can make the defacto stuff work better.

I also noticed that the old ReaAccess send to channel 1/2 >=1/2 stuff is in this dialog. With flat review I can change this, as well as the pre/post fader mode. It's far from practical for speedy use of Reaper, however.

Final thought: could the I/O dialog be hacked around through use of an appModule?

Thanks and apologies for the ramble :)

**Comment by jcsteh** [comment]
The only problem with this implementation is that you unfortunately can't tell whether a send is muted or has its phase inverted. You can toggle it, but you don't know its state. REAPER's MSAA implementation doesn't provide that info and it's difficult/impossible to figure out which exact send we're dealing with so I can query it with the API. While this is annoying, I think it's a relatively minor issue.
