### ISSUE TITLE
FX Parameters dialog for take FX

### ISSUE THREAD

**Issue by jcsteh** [nvaccess/osara#30]
We have access to track FX parameters, but it'd be great to have this for take FX (a.k.a. item FX) parameters as well. This isn't yet possible due to API limitations. I filed [a feature request to add take FX functions to the API](http://forum.cockos.com/project.php?issueid=5554).

**Comment by jcsteh** [comment]
After discussion with Cockos, we now have the required stuff in REAPER 5.20pre and I've implemented it for OSARA. There won't be an OSARA build for this until REAPER 5.20 is released, though. Once that happens, OSARA will depend on REAPER 5.20.

**Comment by chrisbelle2015** [comment]
Splendifourous
and kick-posterior.
