### ISSUE TITLE
FX Parameters dialog: Provide editable text field for numeric values

### ISSUE THREAD

**Issue by tomeckit** [nvaccess/osara#4]
Some parameters has only few values such as on/off, but all sliders has 1000 positions. Other sliders is sometimes broken and you can not changing it's values. So if you try to change something and don't hear anything you don't know is this slider locked or may be it has only few values or anything else. Edit box with possibility to move by arrows allows to change something manually and fast or moving by arrows if we don't know what values this parameter can get. Another advantage is elastic range not only 1000 values. For example if you have filter with parameter "frequency" which can be from 1hz to 22khz and step by 1hz slider must have 22000positions. Pitshifter with step 1 semitone and range from -24 to 24 semitones must have only 48 positions. Another advantage is fast entering value by keyboard in edit box if we know exactly what value we wan't to have.

Sorry for my english.

**Comment by jcsteh** [comment]
If the effect supports formatted values (like the REAPER plugins such as ReaComp and ReaPitch do), the slider already reports the value names. (At least, it does with NVDA, though I've been told this doesn't work for JAWS, which means it isn't supporting the MSAA accessibility standard correctly.) Furthermore, if there are value names, the slider will snap to the next change; e.g. 1 semitone, 2 semitones, etc. So what you want is already occurring.

If the effect doesn't support formatted values, this won't work and there's nothing I can do to improve the slider. The effects don't communicate how many steps there are, so I can't even improve that.

The only thing I *can* do here is allow you to enter a numeric value, but even then, the value will often be meaningless.

**Comment by jcsteh** [comment]
Btw, using a combo box for formatted values breaks effects which expose the formatted value only for the current value; e.g. GSnap.

**Comment by tomeckit** [comment]
but i don't think about combobox control. My be rather edit combo like 
in "filter" in choose fx dialog. I can move by arrows but i can enter 
value too.
BTW. Do you plan to make automation, envelopes etc accessible in Osara?

**Comment by jcsteh** [comment]
An edit combo is actually just a combo box with an editable text field; 
i.e. you still need a complete list of items.

Automation and envelopes is a separate discussion from this report. 
Nevertheless, automation is already possible; you just have to set 
REAPER's automation mode appropriately and start changing parameters. As 
noted in the documentation, OSARA does also support selecting track 
envelopes so you can remove points in time selection, etc.

**Comment by ScottChesworth** [comment]
Just a +1 for the idea of an edit field in addition to the slider. Use case: there are some plugs (amp sims in particular in my experience) that don't expose formatted values, but after some time exploring the generic values I've been able to find where the changes occur. Problem is, moving the slider to those exact positions to cycle through cabinets or the suchlike becomes more time consuming than it would be if there were an edit box I could just type those values into. This would hold true for things like reverb plugins where a user already has a good idea built up from previous use of what those generic values translate into sound-wise.
