### ISSUE TITLE
little issue when deleting last track of the list using the new trackView navigation system

### ISSUE THREAD

**Issue by GianlucaApollaro** [nvaccess/osara#47]
Hi,
I love the new actions about non contiguous selection, but there is a little thing that I don't like about the new track navigation system. If I am on the last track and I delete it, I go back to the master track, being the first one, but that is not always useful when you have many tracks, whereas before the focus remained on the second to last track

**Comment by jcsteh** [comment]
That's rather annoying. My guess is that the last touched track becomes 
invalid in this case, so OSARA resorts to the first (master). I guess I 
can make it use the last track when the last touched track is invalid, 
but I'm concerned that might sometimes happen for other reasons. I guess 
I'll have to try it and see.
