### ISSUE TITLE
Deselect the First Standard Track when only the Master Track Has Focus

### ISSUE THREAD

**Issue by MatejGolian** [nvaccess/osara#49]
Hi,
I haven't tested the current (today's) build of Osara all that much yet, but I think that I found something that has to be addressed.
For testing I inserted a new track into an empty project and than enabled the master track. After that I navigated to the master track with the up arrow. Nothing but the master track was supposed to be selected, when I however tried to insert some new items (as if on the master track) just to see what happens, I found out that from Reaper's point of view the first track (track 1) was still selected. This is to say that the items got inserted on the first track eventhough the first track shouldn't have been selected in the first place. Imfact, in the above scenario nothing should have happened. I therefore came to the conclussion that the first track needs to be be deselected whenever just the master track has focus / is selected. As it is now, we might end up accidentally altering the first track.
Update 1:
From further testing it seems that it would be better to deselect all the standard tracks in the above case as in my second test I had 4 tracks and new items got inserted on the last (4th) track for some reason. Maybe the last track is the one that should be deselected in the end - not the first one. Please, investigate this issue.
Update 2:
This might actually be a Reaper error. I'm not sure, but right now it seems to me that when no tracks are selected, Reaper just inserts new items on the last track whenever an 'insert' action is invoked. Should this be the case you don't have to deal with this issue, of course.
Many thanks for taking a look at this issue.

**Comment by MatejGolian** [comment]
After further testing I've decided to close this issue as it is most likely unrelated to Osara.

**Comment by jcsteh** [comment]
If you move to the master track and then use OSARA's report selection 
command, you'll see that the master track is the only track selected. In 
addition, if you try to toggle mute or the like, you'll see that master 
is the only one affected.

I think what's happening here is that REAPER detects there's no current 
track as far as items are concerned, so it makes an assumption and uses 
the last track. In other words, it presumes the user knows what they're 
doing. Similarly, if you attempt to insert an item when there are no 
tracks at all, REAPER will happily create a new track for you.

**Comment by MatejGolian** [comment]
Thanks Jamie.
I've of course checked it with Osara's report selection action and according to it only the master track was selected. But because I wasn't fully aware of Reaper's default behavior when no tracks are selected, I assumed that there was some error somewhere. Apparently there wasn't one. My mistake.
