### ISSUE TITLE
View FX Chain for Master Track & Toggle FX Bypass for Mastertrack: Activate These with Commands for Standard Tracks

### ISSUE THREAD

**Issue by MatejGolian** [nvaccess/osara#51]
I don't know if this can be done, but could you make it so that the same keyboard commands that display the FX chain and toggle FX bypass for the current track would also work on the master track if it was focused using Osara?
Right now we have to use f and b in case of standard tracks & shift+f and shift+b in case of the master track. This approach could also be extended to the view i/o for current track and view i/o for master track actions as well as those dealing with FX parameters (Osara: View FX Parameters for Current Track & Osara: View FX Parameters for Master Track).

**Comment by GianlucaApollaro** [comment]
I like the idea, but I wouldn't want to remove these actions specific to the master track. I think is quicker to have them as separate actions. For example: if I have a project with several tracks, I could Do ShiftP and control my track and then have a separate action for controlling the parameters of the master track. We would need to have a way to easily go back and forth between the master track and the track we were working with.
