### ISSUE TITLE
Add action feedback for deletion of MIDI events and envelope points

### ISSUE THREAD

**Issue by ScottChesworth** [nvaccess/osara#60]
It's all in the title here really. Thanks in advance if it's possible.

**Comment by jcsteh** [comment]
When you say MIDI events, do you mean in the MIDI Event List or the 
Piano Roll? In the former case, I would have thought it'd be obvious 
since you're in a big list. Also, for various reasons, I can't get OSARA 
messages to work in the Event List without breaking something, usually JAWS.
