### ISSUE TITLE
Suggestions for increasing the productivity of action feedback from peak watcher

### ISSUE THREAD

**Issue by ScottChesworth** [nvaccess/osara#61]
Currently, the action OSARA: report peak watcher peaks speaks in a format that's something like "1, blah point blah. 2: blah point blah." When I'm grabbing readings in quick succession, the channel number preceding the db value decreases how often I can get at the info I seek. Could the channel number be appended instead? I'd ideally like to see separate actions to report left and right channels too, as currently there's not a way of just focusing on the right hand side of a mix for example without sitting through lefty db values first each time.

**Comment by jcsteh** [comment]
I could provide separate actions. I didn't do this in the first place 
because I was trying to avoid consuming too many additional keystrokes; 
we're running out of those as it is. However, if this is necessary for 
decent productivity, sure.

Should we still keep the action to report all channels in case someone 
cares about all the info at once? I'm not sure how to make appending the 
channel number make sense. 0dB 1, 0dB 2 doesn't really seem intuitive at 
all.

**Comment by ScottChesworth** [comment]
Definitely don't scrap the action to report all channels at once yet.
I'd suggest appending "Channel 1" and "Channel 2". The word will
separate the db value from the channel number. It's a longer spoken
message technically, but most people won't wait around to hear the end
of it anyway, the channel notification is pretty much only there for
people who're just starting out.

**Comment by jcsteh** [comment]
But making the message longer is a contradiction in making this more efficient. You're arguing that you have to wait longer to hear the values right now, but if you append "channel", you're only making things better for the left channel. The right channel is potentially even more disadvantaged.

**Comment by ScottChesworth** [comment]
Ah, in my head, the idea of appending channel didn't apply to the
existing action that reads both channels in one hit. Sorry, probably
should've pointed that out. Given how many people have passed comment
on some level that they preferred readings for separate channels
anyway, perhaps it would be a wise move to replace the existing action
rather than overcomplicating this by keeping it around. Do you agree
that the db reading coming first and appending channel afterward would
be efficient if we could read meters for channels individually?

**Comment by jcsteh** [comment]
If the actions are for individual channels, reading the channel at all 
is redundant, no?

**Comment by ScottChesworth** [comment]
Fair point. I requested the channel to be read because I can pretty
much guaranty people will expect it to be, but I guess the answer to
that is "this is why Jamie spent time making a shortcut help mode even
though he didn't want to". hahaha. I'd be fine seeing the appended
messages dropped altogether personally.

**Comment by jcsteh** [comment]
If you think people will expect it to be, I can just do it; it's not 
much extra effort. I guess a bit of extra handholding never hurt anyone.
