### ISSUE TITLE
Can non-contiguous selection of items be made possible when spanning multiple tracks?

### ISSUE THREAD

**Issue by ScottChesworth** [nvaccess/osara#64]
It's possible that this is already possible and I just don't understand the UX, but if not, is there any magic you can work to make it so? For example, if I wanted to selected the first item on track 1, 3, 5, 7, and 9 of a project, I'd have to do this individually at the moment. That's not the same UX as our sighted peers get. They can shift-click to add items to selection from wherever.

**Comment by jcsteh** [comment]
I don't really follow. Sighted users still have to shift click on the 
items. Similarly, we move to the items and press shift+space. I guess 
it's a bit slower for us, but I don't really understand how you're 
suggesting we make this faster.

**Comment by ScottChesworth** [comment]
Hey Jamie,

Perhaps I explained badly. My issue isn't speed, it's that
non-contiguous selection seems to be limited to selecting items on a
single track, which is a different UX from what the sighties have at
their disposal. They can shift+click to add items to selection
irrespective of what track they reside on.

Does that clarify?

**Comment by jcsteh** [comment]
You can already do that. You just enable non-contiguous selection and then use the contiguous track selection commands. So, if you're on track 1 and you want to move to track 3 without affecting selection, press shift+downArrow twice.

**Comment by ScottChesworth** [comment]
Aha, my bad! I was letting up on shift once contiguous selection mode
was activated. Cool, feel free to close this one then. I've jotted
down a note to make mention of the fact that shift has to stay held
down when it comes to writing training material, just in case there's
someone else out there who's this daft :P

**Comment by jcsteh** [comment]
I've added a note to the readme to clarify this.
