### ISSUE TITLE
Toggling master track

### ISSUE THREAD

**Issue by ScottChesworth** [nvaccess/osara#67]
Sort of two issues here, even though I know that's annoying.
1. Currently, we don't seem to have action feedback for toggling master track visibility? Can we?
2. The CTRL+Alt+M keystroke which is specified in the keymap and is also mentioned in the view menu doesn't seem to work on this system, even with a screen reader pass through command before it, and even with no screen reader loaded! Guessing this is Reaper specific rather than OSARA, but wanted to see whether you can reproduce in the first instance.

**Comment by jcsteh** [comment]
Regarding the second issue, I can't test this, as I have a system wide 
shortcut bound to control+alt+m. If you wanted to be sure it wasn't 
OSARA, you could remove OSARA temporarily, run REAPER, press the 
shortcut and verify that it ran using the the Actions menu (since it 
shows recent actions).
