### ISSUE TITLE
Action to reset peak watcher values

### ISSUE THREAD

**Issue by ScottChesworth** [nvaccess/osara#68]
It would be uber productive if this could be done without needing to load the peak watcher dialogue, thus avoiding resetting keyboard focus. My rationale is that sighted users will often drag and resize windows so as to have their meters visible and reachable at any given point, so they can observe and reset metering without deviating far from the task at hand.

**Comment by jcsteh** [comment]
It's true that opening the dialog takes focus away, but when you return, focus is back exactly where you left it. Thus, focus isn't actually "reset". My original reason for doing it this way is that you can still do this quite fast (alt+shift+p then alt+r) without wasting an additional key binding.

If you still really want the action, I can add it, but I'm trying to avoid wasting bindings here.

**Comment by ScottChesworth** [comment]
That's valid assuming that you're using peak watcher from the TCP. It doesn't hold up so well when trying to gauge the gain reduction being applied by a compressor without a lot of closing and reopening of the fx window, for example.
