### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by jcsteh** [nvaccess/osara#70]
We need an installer. I was going to work on this towards the end, but OSARA already has a growing number of users and not having an installer is causing a lot of confusion.

**Comment by MatejGolian** [comment]
How come the 2 DLLs don't fight with each other?
If my test results are correct, 32 bit Osara runs just fine with a 64
bit Reaper (as expected) so, when both Osara DLLs are present in the
user folder, how do you make sure that Reaper x64 uses the 64 bit
version of Osara?
Just currious. :D<div id="DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2"><br />
<table style="border-top: 1px solid #aaabb6;">
	<tr>
		
		<td style="width: 470px; padding-top: 20px; color: #41424e;
font-size: 13px; font-family: Arial, Helvetica, sans-serif;
line-height: 18px;">Tento email byl odeslán z počítače bez virů,
chráněného programem Avast. <br /><a
href="https://www.avast.com/sig-email" target="_blank" style="color:
#4453ea;">www.avast.com</a> 		</td>
	</tr>
</table>
<a href="#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2" width="1" height="1"></a></div>

2016-02-17 11:33 GMT+01:00, James Teh <notifications@github.com>:

**Comment by jcsteh** [comment]
A 64 bit process can't load 32 bit dlls and vice versa. However, on a 64 
bit system, REAPER doesn't seem to complain. So, this way, you can use 
either or both. :)

**Comment by MatejGolian** [comment]
Thanks, I see. :)<div id="DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2"><br />
<table style="border-top: 1px solid #aaabb6;">
	<tr>
		
		<td style="width: 470px; padding-top: 20px; color: #41424e;
font-size: 13px; font-family: Arial, Helvetica, sans-serif;
line-height: 18px;">Tento email byl odeslán z počítače bez virů,
chráněného programem Avast. <br /><a
href="https://www.avast.com/sig-email" target="_blank" style="color:
#4453ea;">www.avast.com</a> 		</td>
	</tr>
</table>
<a href="#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2" width="1" height="1"></a></div>

2016-02-19 12:38 GMT+01:00, James Teh <notifications@github.com>:
