### ISSUE TITLE
Possible Bug with item deletion

### ISSUE THREAD

**Issue by Justinmac84** [nvaccess/osara#72]
Hi,

I have spoken to a few others about this issue and it appears to be one of those annoying intermittent ones but I get it quite a lot running the latest version of 32-bit Reaper, Osara and NVDA. 

Often, when you delete items, particularly more than one, you cannot select items using the control cursor left and right shortcuts until you have moved your cursor a substantial amount from where you are. Sometimes it's only a bar or two but more often, you have to go right back to the start of the project, or presumably the end, in order to get the control left and right actions to work again. 

Hopefully other people can chime in on when they experience this, but I know that Derek experiences it occasionally too. 

Thanks for anything you can do.

**Comment by ScottChesworth** [comment]
Aha, I've heard this one coming from a few people, but haven't been
able to reproduce it here yet so haven't filed it.

When it occurs, do the actions that should select previous or next
item provide any feedback even though they're not navigating through
the timeline as expected?

Can anyone provide consistent steps to reproduce? Pretty sure Jamie
will want something more than "sometimes it happens" to chase down a
cause if possible.

**Comment by jcsteh** [comment]
I fixed an issue like this back in November last year (a4f71a99). I 
don't mean to patronise, but it'd be great if you can triple check 
you're running the latest OSARA, just so we can be absolutely certain 
we're not chasing a bug I've already fixed. Thanks for your patience.

**Comment by Justinmac84** [comment]
I will do that tomorrow.

If you haven't heard back from me by the day after, that is Friday UK 
time, please feel free to close the issue. I think you may be right and 
that I am not as up-to-date as I should be.

Thanks very much and sorry for the inconvenience if it turns out to be a 
wild goose chase,

Justin

**Comment by jcsteh** [comment]
Closing as per above comment. Please reopen if the problem persists.
