### ISSUE TITLE
Select from cursor to end of project

### ISSUE THREAD

**Issue by leonardder** [nvaccess/osara#73]
Could a "Select from cursor to end of project" action be added and bound to shift+end, similar to the Select from cursor to start of project action?

**Comment by GianlucaApollaro** [comment]
Hi,
I mapped shift + end to the sws action called sws/aw Select from cursor to end of project (item and time selection). Doesn't it work for you?

**Comment by leonardder** [comment]
A, I see. At the time of writing, I didn't have SWS installed.
Anyhow, in my opinion, this should be an action which is supported by Osara without SWS installed. Having an action for selecting to start of project and not having one for selecting to end seems to be slightly inconsistent.

**Comment by GianlucaApollaro** [comment]
If you noticed the actions that selects to start says custom. I created 
that action by chaining 3 actions together. I didn't create an 
equivalent for select to end because sws already had one so Iput that 
one in the keymap. Sws is needed anyway for osara

Il 19/02/2016 09:23, Leonard de Ruijter ha scritto:

**Comment by jcsteh** [comment]
Actually, OSARA doesn't technically depend on SWS. It just supports some 
actions that SWS provides. That said, it does seem pointless to 
duplicate actions that SWS provides, especially given that it's a very 
common REAPER extension.

**Comment by leonardder** [comment]
I assume there is no select from start to cursor action in SWS, which we can use instead of the custom one to unify things a bit?

**Comment by GianlucaApollaro** [comment]
You are correct

Il 19/02/2016 12:02, Leonard de Ruijter ha scritto:

**Comment by jcsteh** [comment]
I know SWS already has this, but since we're already doing it for select to start, I think we may as well do it for select to end as well to be symmetrical. And since it's just a chained action, it's not overly complex/bloatworthy.

**Comment by ScottChesworth** [comment]
Good call IMO, thanks. Symmetry ftw, etc.

**Comment by jcsteh** [comment]
Would someone else mind taking care of this? It's just a key map change. 
Just shoot me the revised reaper-kb.ini once done.

**Comment by ScottChesworth** [comment]
Done. Keymap is in the mail.

**Comment by leonardder** [comment]
Symmetry was actually the main reason why I filed this. Thanks for fixing!
