### ISSUE TITLE
Quick routing

### ISSUE THREAD

**Issue by meckito** [nvaccess/osara#79]
Scenario: you creating one track as send for fx and you can send other tracks but not all to this track. Now you can wait few seconds for every track before adding next. if you can send 20 tracks you can wait about a minute without doing anything. If you can make this for few other tracks you must wait few minutes without doing anything. Good idea will be make routing window when you can select source and destination tracks, set other parameters such as in and out channels and fast send any tracks to another.

**Comment by jcsteh** [comment]
I don't understand what you're saying about waiting. You can just keep adding new sends from the I/O window. No waiting is required. All of the options you need are now accessible in that window. Duplicating that UI gives no benefits.

**Comment by meckito** [comment]
As I know if you can add new send you must select track and wait a 
second be cause there is no any button to send it to other track. It is 
done automatically after one or two second after selecting it.

**Comment by jcsteh** [comment]
Hit alt+downArrow to expand the combo box, select your track, then press enter to accept. This eliminates the delay and also gives you as much time as you need to select the track.

**Comment by chrisbelle2015** [comment]
I don't know if there is anything that can be done, but I think what 
he's wanting is a way to control that automatic behavior.
You've made it possible to go to an alternative combo box with the alt 
down arrow, and there it doesn't automatically populate, but you must 
get out of there,
once you make a send selection or reaper goes back to it's automatic 
behavior.
I guess there's no way to make reaper be passive, and let you stay in 
that window and keep making selections.
I couldn't get it to work, those combo boxes only worked as you stated 
if I pressed enter after down arrowing and making a selection,
and pressing enter again, otherwise reaper went back to automatic behavior.
Does a sighted person have more control of this?
Or is this just reaper default behavior, and that's that?
yes, the accessibility implemented is very helpful, but if you're not 
very careful you will get unwanted sends.

**Comment by chrisbelle2015** [comment]
yes, you most definitely made it doable.
Very much appreciated.
But it's one pass at a time,
if you try and do more than one thing in there, then it's musical chairs 
as usual and very hard to tell what you did.
The obvious work around is to keep going back in there and do each send 
piece meal, there is an option to get sends or receives from all other 
tracks, that's a nice option but if you want to do some complex routing,
you'll have to do it in several passes.
If that's the way it's got to be I can live with that,
it's definitely better than it was, but if it can be improved at all,
for multiple tasks, then that would be god.
Much appreciated.

**Comment by jcsteh** [comment]
Not at all. Alt+downArrow, select send, enter. Alt+downArrow, select 
another send, enter. Keep going until you're done.

**Comment by meckito** [comment]
In Reaaccess if you select few track for example 1, 5, 8, 9, 12, 15, and 
17 you can hit shift context menu, send it to one track with one step. 
Now you must repeat alt +arrow and select track for every tracks. There 
is no problem when you can send 2 or 3 tracks. Problem appear if you can 
send for example 15 tracks but this are not all tracks in project. 
Creating folder not always is good method.

**Comment by chrisbelle2015** [comment]
Ok, looks like it does indeed work well.
The trick is that no matter what you do, you always have to do that alt 
down arrow even if you want to back out of the dialogue.
And hit enter, never escape or move the arrows unless you do the alt 
down arrow or you'll get that automatic behavior.
What is interesting is that adding sends didn't show up in the undo list 
while the recorder was engaged, but did so when playback was running.
I could manually delete them from the dialogue, but I often use the undo 
in the edit menu to see if things went as I expected when doing actions, 
and they weren't there.
Well, it's reaper after all 'grin'.
Thanks for your hard work.

**Comment by jcsteh** [comment]
I didn't realise REAPER provided a context menu for fast routing, but it seems it does indeed. If that's what you're wanting, that's totally valid. What I don't think we need is a full window for routing configuration, since at that point, you may as well just use the normal routing window.

**Comment by jcsteh** [comment]
Thanks again for the info about this context menu. I never even knew it existed. That certainly makes things much faster... particularly if you have multiple tracks selected!

Note that I've used alt+applications, as we may need to support shift+f10 for context menus some day, so shift isn't ideal.

**Comment by chrisbelle2015** [comment]
hey, this is great.
I'll use this method of sends and hardware outs even for simple routing, 
as it doesn't try to populate for me, or I don't have to worry about did 
I make a wrong move and goof it up.
And the master send is in there too,
a nice toggle, with the regular method I have to use object nav to check 
and uncheck that.
This is much better.
