### ISSUE TITLE
Consistent action feedback when creating new tracks

### ISSUE THREAD

**Issue by ScottChesworth** [nvaccess/osara#82]
Currently, all screen readers I've tested OSARA with speak some form of spurious info when triggering the action Custom: insert unnamed track. It's fairly low priority I know, but if it's possible for OSARA to override this behaviour with a single message consistent across screen readers such as "Enter name for new track", it'd be a much smoother ux for newbies.

**Comment by jcsteh** [comment]
Pretty difficult I'm afraid. We can't just override the speaking of 
normal controls with other speech. I notice ReaAccess has this problem 
too (and probably ReaEar). The only way would be to tweak the 
accessibility for a few controls, which I can possibly do, but it's very 
tedious work in this case.

**Comment by ScottChesworth** [comment]
Ah ok, feel free to close and raise it with Justin instead if the time
comes when all the essential stuff has been tidied up.

**Comment by jcsteh** [comment]
Actually, I figured out a creative way to do this. :) It's a minor rough edge, but it really does get annoying, even for me. This also fixes the garbage you hear when you alt+tab in.

**Comment by ScottChesworth** [comment]
Running 2016.1pre-25,a9bc1047, I'm not hearing any difference with
NVDA 2016.1 when triggering the Custom: insert unnamed track action or
Alt+Tabbing into Reaper.

If there's anything I can do to help troubleshoot, shout.

**Comment by jcsteh** [comment]
Spoke to @ScottChesworth. The code works fine; he just goofed. :)

**Comment by leonardder** [comment]
It seems that, when i press f2 while I have no tracks in a project, it still says track name. So, speaking the label should be limited to situations where there actually is a track to rename.
