### ISSUE TITLE
editing custom actions in reaper

### ISSUE THREAD

**Issue by chrisbelle2015** [nvaccess/osara#83]
hard to edit custom actions with many consolidated actions.  Reaper seems to loose focus, when alt tabbing away, can tediously edit one action out of a list but can not select multiple actions to delete for instance, when trying to edit a volume custom action to make 10 instead of 20 consolidated actions, can use object nav to do the job but is difficult.

**Comment by jcsteh** [comment]
This is something Cockos will need to fix. Hacking around it in OSARA isn't worthwhile.

That said, I don't really understand the exact issues. Sorry, but I'm going to need thorough details. What exactly are you doing, what happens and what did you expect instead? Why can't you select multiple? What happens when you do? I can't report this to Cockos without thorough details.

**Comment by chrisbelle2015** [comment]
Ok let's see if I can make myself clearer.
You do know you can make custom actions with combining other actions, 
for instance, I have the alt down and up arrow volume actions
as custom actions but repeated several times to get custom intervals 
like half a db or 1 db because as you know you only get 1 twentieth of a 
db movement from those actions.
It's pretty easy to make them, but when you want to edit them, when you 
try and do that you can't select more than one action to delete at a time.
It looks like a list view so you should be able to shift and up and down 
arrow and grab 10 of them to delete, but when you do that only one get's 
deleted when you hit the button.
so it's very tedious to edit those actions.
So what I've been doing is removing them and re-doing them.
where this might be important is when combining actions of different 
types, complex custom actions
I managed to do it with object nav but if I alt-tab away from the 
dialogue after deleting an action, then it won't focus again,
  it looks like it's gone.
Scott reproduced the same thing, perhaps he can explain it better than i 
can.
Seems pretty straight forward to me, but if you haven't done it then you 
know how that goes,
'smile'.
YOu know when you create custom actions you go to the first list and do 
NVDA num pad enter and it double clicks and puts the actions in the 
second list.
So you can string them together.
I was trying to take some of the actions out of the second list, in that 
string.
That's where it got hard, and the dialogue went away,
and maybe there's a particular way to select more than one action in 
that second list, but I haven't
tagged it yet.
So I hope this is clearer now.
If I need to I'll make a little recording and show myself doing it.

**Comment by chrisbelle2015** [comment]
hey Jamie, perhaps you don't have any custom actions to test with, you 
can grab my ones from drop box I posted earlier.
Try and delete some actions from the second list that shows the string 
of single actions
there will be 10 of them.
that is 10 times 1 twentieth of a db which makes half a db.
I assigned these to alt page up and down arrow respectively.
If you try and delete actions from the second list, by pressing enter on 
the button focus goes away.
If you do it with object nav you can press on the ok button with object 
nav or mouse cursor, but you can only delete one action at a time.
so it will be tedious to have to go back in there and delete say 10 
actions if you want to say change a 1 db volume nudge to a half db 
volume nudge.

**Comment by jcsteh** [comment]
Sure, I could test this myself, but since you're reporting the issue 
anyway, I figured it'd be easier for you to give a description I can 
just pass on to Cockos rather than me having to write it up separately.

The only thing I'm not clear on is why you have to alt+tab out of the 
dialog in the first place. Sure, it doesn't get focus when you alt+tab 
back in, but why are you alt+tabbing out anyway?

I suspect even sighted people can't select multiple items and remove 
them all at once. So the question is: why is this any harder for a 
screen reader user?

I'm guessing you're hitting the problem that sometimes occurs in REAPER 
where hitting a Remove button causes complete focus loss, hence the 
alt+tab, but you didn't mention that occurring, so I'm not entirely clear.

**Comment by chrisbelle2015** [comment]
I thought I had mentioned it.
I alt tabbed away to try and get focus back yes I can delete an action 
with object nav but I was trying to do it with the keyboard, and once I 
hit the button, focus goes away like you said.
I didn't know if sighted users could do multiple removes, but I thought 
I saw something that said, select the things you want to remove, so I 
thought it might be possible to do multiples,
never mind if I'm asking for something which isn't possible for sighted 
people.
It's hard to know sometimes,
since I'm not a sighted person 'grin'.
Anyway, I don't mind doing what ever to help make this more clear,
or help you out,
I'm not good at step by steps from memory,
especially when I'm experimenting,
it's one thing to do it and tell a student while your doing it and have 
them follow along, but my meandereing explanations which seem to be good 
for my students sometimes drive logical programmer types with giant 
brains like your self
crazy,
not that I can't do step by steps but reaper is still new to me,
so knowing what's normal and what's not well, you know how it goes.
YOu just say jump, and I'll say how high,
and we'll get it figured out one way or the other 'grin'.
Thanks for all you do.

**Comment by jcsteh** [comment]
Thanks; that gives me what I need. In short, the real problem here is the focus loss when one hits Remove. Multi-selection and removal would be nice, but I suspect that's not possible even for sighted people, so it's somewhat less important.

**Comment by chrisbelle2015** [comment]
I understand.
Well, so far it's not that big a deal to delete and just remake my actions.
But even if we have to delete actions in that second list one at a time,
if we didn't loose focus and could move around and see what we did that 
would make it easier.
Do what you can, and thank you.

**Comment by ScottChesworth** [comment]
I'm almost certain that sighties can select and remove multiple
actions from that second list. Can't verify it until early next week
unfortunately. The focus loss issue is the priority anyway IMO.

**Comment by chrisbelle2015** [comment]
One would think so.

But we're talking reaper here,
'grin'.

**Comment by jcsteh** [comment]
According to Justin from Cockos, nope, sighties can't multiple select either. He's fixing the remove focus loss issue, though.

**Comment by jcsteh** [comment]
Oh, and he's also changing the label from Remove selected to Remove action, since he agrees it's potentially misleading. :)

**Comment by chrisbelle2015** [comment]
Nice.
Well, at least we know now 'grin'.

**Comment by chrisbelle2015** [comment]
Very cool.

**Comment by jcsteh** [comment]
Fixed in REAPER 5.20pre21.
