### ISSUE TITLE
Reporting Effects for Takes

### ISSUE THREAD

**Issue by Justinmac84** [nvaccess/osara#84]
Hi, 

Please could there be an option in Osara preferences to provide feedback informing the user of the effects applied to takes in the same way as effects on tracks are currently reportable. 

When dealing with a large project, either containing many items and/or tracks, it would be useful to see, at a glance, what effects are where. 

Likewise, reporting an items mute and locked states, if this is not already supported, would be very useful. 

Thanks a lot, 

Justin

**Comment by ScottChesworth** [comment]
I'm fairly sure Jamie will want the mute and lock states of items as
separate issues, so will file those now.

**Comment by Justinmac84** [comment]
thanks and sorries,

New to Github ettiquette :)

Justin

**Comment by jcsteh** [comment]
No problem. Scott is used to my tendency to split things up into little 
tasks. :) Interestingly, in this case, I'll probably do them both as one 
job because it touches the same area of code, but neither Scott or you 
could have known that.
