### ISSUE TITLE
Action feedback for item mute state

### ISSUE THREAD

**Issue by ScottChesworth** [nvaccess/osara#85]
When navigating using the actions item navigation: move to previous item and item navigation: move to next item, it would be very useful if OSARA reported whether an item is muted. I think this info should come after the item number, but before the item name. I think we'd only need to hear when an item is muted.

**Comment by jcsteh** [comment]
It's worth noting that saying mute before the name is inconsistent with tracks, where we say muted after the name. Can we justify this inconsistency or do we need to rethink something?

**Comment by ScottChesworth** [comment]
Eek, my bad for not being specific enough in the previous issue for
tracks. Would it be a huge headache to re-jig the reporting of whether
a track is muted before we hear the track name? IMO, this is the most
productive sequence of announcements.

**Comment by jcsteh** [comment]
> What about armed and soloed? You could end up with something like 1 muted armed soloed phase inverted snare". Is the name really less important than all of that from an efficiency standpoint? And if muted, etc. is really more important than the track name, is it also more important than the track number? And if not, why not? I'm not sure I have a strong opinion here, but I ask these questions so the final UX is solid and well justified. If we can't explain why, we're probably doing it wrong. :)

Btw, despite all of this, I assume FX should definitely come last? I think so that info is far less important and I think most would agree.

**Comment by stickbear2015** [comment]
Here's my opinion.
All of the info's important, yes fx should be last, but all of this should be toggleble from the preferences of osara, so people can pick and choose what gets verbalized.
Or am I overthinking something. :-)
Just my opinion.

**Comment by ScottChesworth** [comment]
Fair point Jamie. Thinking harder about this, I actually can't justify
why mute should come first beyond it'd suit my workflow. Let's keep
mute reports after the item name then for consistency.

In an ideal world, we'd be able to choose the order of such status
reports in the OSARA config dialog, but I'm guessing that the UI for
such functionality would be a big time sucker to develop?

**Comment by jcsteh** [comment]
Yes, that sort of UI is a huge time sink. Aside from that, though, it's also a very slippery slope. The more complex your config gets, the less intuitive it becomes.

As for making whether it's spoken at all configurable, sure, that could be done. However, I very much doubt most people would want to disable mute, arm, etc., so this would probably never be used. Saying "make it configurable" is sometimes a poor excuse for "we can't be bothered figuring out a proper UX". :)

All of that said, there may be a good argument for having configurable announcement of track names. Scott, I get the impression you tend to deal more with track numbers than names. Would this work for you? And should that also apply to item names as well?

**Comment by jcsteh** [comment]
Actually, one justification for items and tracks being inconsistent is that item names are possibly less necessary than track names. If you're playing, you'll hear the item when you jump to it; the name is secondary. In contrast, with tracks, you'd have to solo to know what the track was. Does this seem logical to anyone else though?

**Comment by ScottChesworth** [comment]
I tend to rely on track names and item numbers when zipping around a
project. The naming scheme is rigid here wherever possible so I can
tweak stuff on the fly with ReaConsole without actually moving to a
track.

When you say make track name configurable, are you talking about a
toggle that decides whether it's spoken, or the ability to choose when
it's spoken in among the info we hear when moving to a track? If the
former, I can't say I'd ever use that personally, and can't really
imagine why anyone would want to disable track names being spoken
entirely. If the latter, that'd be neat, but how would the UI work?
It's not possible to set a value for when track name would be spoken
among a predefined number of messages that'll be spoken really is it,
because one track could be muted, soloed, and have fx inserted,
whereas another could just be muted, and another could just have fx
inserted.

Your justification for difference between items and tracks makes a lot
of sense here btw, but it would do, because it's what I wanted :P

**Comment by chrisbelle2015** [comment]
I tend to like the name first.
That tells you right off what you're working with.
but people are all
different.
Ct has it where you can configure what's read first, but then we are 
headed in to lots of snakey code,
but what ever we do let's make it consistant and the same for everything.
