### ISSUE TITLE
OSARA: Report Peak Watcher value for channel 1 of second track - Shortcut Missing

### ISSUE THREAD

**Issue by MatejGolian** [nvaccess/osara#88]
I just installed the latest build and I noticed a quite strange thing.
The shortcut for OSARA: Report Peak Watcher value for channel 1 of second track stopped working for some reason. So I went and assigned alt+shift+f9 to this action, but first I had to answer this rather unexpected question:

"This key is already mapped to the action:
(unknown)
Override mapping?"

What could be causing this?

**Comment by jcsteh** [comment]
This happened in @GianlucaApollaro's first key map update after I committed the new Peak Watcher code.

Gianluca, just to check, are you always basing the key map on the one provided with OSARA or are you maintaining your own based on my commit notes? This problem suggests something got out of sync between us somehow. We need to make sure we're keeping this in sync, so it's probably best for you to clean import the key map from OSARA before making any changes for submission. Of course, if you're doing that already, there's nothing to change!

**Comment by GianlucaApollaro** [comment]
Hi,
I use the one you provide everytime and modify that if need be

Il 11/03/2016 15:08, James Teh ha scritto:
