### ISSUE TITLE
Can't compile, no MUI2.nsh

### ISSUE THREAD

**Issue by djn40** [nvaccess/osara#89]
Can't compile useing scons with python 2.7.8.
I get an error about MUI2.nsh.
I have makensis and visual studio installed, any tips?

**Comment by jcsteh** [comment]
That suggests you don't have NSIS installed correctly or perhaps you chose not to install the Modern User Interface. Either way, this isn't a bug in OSARA; I'm just using the latest official version of NSIS.

**Comment by jcsteh** [comment]
When yu say you have makensis installed, do you mean the official NSIS package or something else which just contains makensis? You should be using [this official NSIS 2.50 installer](http://prdownloads.sourceforge.net/nsis/nsis-2.50-setup.exe?download).
