### ISSUE TITLE
Speak the toggle master mono command

### ISSUE THREAD

**Issue by Cleversn** [nvaccess/osara#94]
Osara should speak when pressing shift+f9 to toggle master mono, the same way it speaks commands like play, stop and soloed/unsoloed. Currently it speaks nothing.

**Comment by mulcahy1000** [comment]
I took a quick look at this one, and didn't see an obvious way for Osara to get at this info from the Reaper API. Seems like it might be hidden in the master track send info for hardware outputs, but nothing I tried in that regard worked. Anyone have any ideas as to whether this is technically feasible?

**Comment by jcsteh** [comment]
That action is a toggle action, so you can query its state. See
postToggleRepeat for an example.

**Comment by mulcahy1000** [comment]
Just submitted a pull request which should resolve this issue. Thanks for the pointer.
